### ISSUE TITLE
 import '../app.css'; causing Acorn parse error

### ISSUE THREAD

**Issue by djs959** [mainmatter/sheepdog#240]
When vite loads I get the below error from the acorn parser, 
```
 error SyntaxError: Unexpected token (1:0)
    at pp$4.raise (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:3640:13)
    at pp$9.unexpected (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:766:8)
    at pp$5.parseExprAtomDefault (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2984:8)
    at pp$5.parseExprAtom (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2979:17)
    at pp$5.parseExprSubscripts (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2763:19)
    at pp$5.parseMaybeUnary (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2721:17)
    at pp$5.parseExprOps (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2649:19)
    at pp$5.parseMaybeConditional (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2632:19)
    at pp$5.parseMaybeAssign (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2599:19)
    at pp$5.parseExpression (file:///Users/dan/dev/svelte-booker/node_modules/acorn/dist/acorn.mjs:2562:19) {
  pos: 0,
  loc: Position { line: 1, column: 0 },
  raisedAt: 1
}
```

The error message lacks context so I added a `console.log` to the `asyncTransform.transform()` catch block and the error appears to result from parsing the css file loaded from the  `import '../app.css';` in my layout.svelte. I'm using tailwindcss. 

If I remove the import I no longer get the parse error, but of course my css doesn't load.

**Comment by beerinho** [comment]
Hey @djs959, please can you make a minimal reproduction so we can take a look, trying this locally I don't encounter the issue you mentioned. If you haven't already encountered it, https://www.sveltelab.dev/ is great for creating minimal reproductions

**Comment by beerinho** [comment]
Hey @djs959, thanks for bringing this to our attention. As @paoloricciuti mentioned, it's not showing an actual issue but rather displaying the caught error when the parser tries to parse a non-parseable file. We've updated it and it will be part of the next release so keep your eyes peeled for that 👀. Here's the release PR - https://github.com/mainmatter/sheepdog/pull/234
