### ISSUE TITLE
asyncTransform & ts

### ISSUE THREAD

**Issue by jycouet** [mainmatter/sheepdog#241]
When I add
```ts
import { asyncTransform } from '@sheepdog/svelte/vite'
import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    sveltekit(),
    asyncTransform(), // <- this
    ]
 })
```
I get:
```
No overload matches this call.
  The last overload gave the following error.
    Type 'Promise<{ name: string; transform(this: TransformPluginContext, code: string, id: string): Promise<{ code: string; map: any; } | undefined>; }>' is not assignable to type 'PluginOption'.
      Type 'Promise<{ name: string; transform(this: TransformPluginContext, code: string, id: string): Promise<{ code: string; map: any; } | undefined>; }>' is not assignable to type 'Promise<false | Plugin<any> | PluginOption[] | null | undefined>'.
        Type '{ name: string; transform(this: TransformPluginContext, code: string, id: string): Promise<{ code: string; map: any; } | undefined>; }' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.
          Type '{ name: string; transform(this: TransformPluginContext, code: string, id: string): Promise<{ code: string; map: any; } | undefined>; }' is not assignable to type 'Plugin<any>'.
            Types of property 'transform' are incompatible.
              Type '(this: TransformPluginContext, code: string, id: string) => Promise<{ code: string; map: any; } | undefined>' is not assignable to type 'ObjectHook<(this: TransformPluginContext, code: string, id: string, options?: { ssr?: boolean | undefined; } | undefined) => TransformResult | Promise<...>> | undefined'.
                Type '(this: TransformPluginContext, code: string, id: string) => Promise<{ code: string; map: any; } | undefined>' is not assignable to type '(this: TransformPluginContext, code: string, id: string, options?: { ssr?: boolean | undefined; } | undefined) => TransformResult | Promise<...>'.
                  The 'this' types of each signature are incompatible.
                    Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.24.3/node_modules/rollup/dist/rollup").TransformPluginContext' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/rollup").TransformPluginContext'.
                      The types returned by 'getModuleInfo(...)' are incompatible between these types.
                        Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.24.3/node_modules/rollup/dist/rollup").ModuleInfo | null' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/rollup").ModuleInfo | null'.
                          Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.24.3/node_modules/rollup/dist/rollup").ModuleInfo' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/rollup").ModuleInfo'.
                            Types of property 'ast' are incompatible.
                              Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.24.3/node_modules/rollup/dist/rollup").ProgramNode | null' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/rollup").ProgramNode | null'.
                                Type 'ProgramNode' is not assignable to type 'ProgramNode | null'.
                                  Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.24.3/node_modules/rollup/dist/rollup").ProgramNode' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/rollup@4.14.3/node_modules/rollup/dist/rollup").ProgramNode'.
                                    Type 'ProgramNode' is not assignable to type 'Omit<Program, OmittedEstreeKeys>'.
                                      Types of property 'body' are incompatible.
                                        Type '(import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Directive | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Statement | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_m...' is not assignable to type '(import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Directive | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Statement | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_m...'.
                                          Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Directive | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Statement | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_mo...' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Directive | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Statement | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_mo...'.
                                            Type 'ExpressionStatement' is not assignable to type 'Directive | Statement | ModuleDeclaration'.
                                              Type 'ExpressionStatement' is not assignable to type 'Directive | ExpressionStatement'.
                                                Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").ExpressionStatement' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").ExpressionStatement'.
                                                  Types of property 'expression' are incompatible.
                                                    Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Expression' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Expression'.
                                                      Type 'ArrayExpression' is not assignable to type 'Expression'.
                                                        Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").ArrayExpression' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").ArrayExpression'.
                                                          Types of property 'elements' are incompatible.
                                                            Type '(import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Expression | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").SpreadElement | null)[]' is not assignable to type '(import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Expression | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").SpreadElement | null)[]'.
                                                              Type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").Expression | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.6/node_modules/@types/estree/index").SpreadElement | null' is not assignable to type 'import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").Expression | import("/home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/@types+estree@1.0.5/node_modules/@types/estree/index").SpreadElement | null'.
                                                                Type 'ArrayExpression' is not assignable to type 'Expression | SpreadElement | null'.ts(2769)
```

There is a specific vite requirement ? or tsconfig ? 
(I'm on "vite": "5.4.10")

**Comment by paoloricciuti** [comment]
Do you have an actual reproduction? Is this a fresh kit project?

**Comment by jycouet** [comment]
I added it again in the same project... And of course... No more ts issues in config! 🤔 (still "vite": "5.4.10").
So I don't really know, I'll do a branch next time directly.

Now, I added `task.restart`, and it seems to work well 👍 https://github.com/jycouet/jyc.dev/blob/0ba06313cfd038e1400f23d4f7af2e5386c4a387/src/routes/stats/wolf/%2Bpage.svelte#L30
But I get some errors in the terminal: 
```ts
SyntaxError: Unexpected token (7:0)
    at pp$4.raise (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:3640:13)
    at pp$9.unexpected (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:766:8)
    at pp$5.parseExprAtomDefault (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2984:8)
    at pp$5.parseExprAtom (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2979:17)
    at pp$5.parseExprSubscripts (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2763:19)
    at pp$5.parseMaybeUnary (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2721:17)
    at pp$5.parseExprOps (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2649:19)
    at pp$5.parseMaybeConditional (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2632:19)
    at pp$5.parseMaybeAssign (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2599:19)
    at pp$5.parseExpression (file:///home/jycouet/udev/gh/jycouet/jyc.dev/node_modules/.pnpm/acorn@8.14.0/node_modules/acorn/dist/acorn.mjs:2562:19) {
  pos: 360,
  loc: Position { line: 7, column: 0 },
  raisedAt: 361
}
```
This time I added a branch: https://github.com/jycouet/jyc.dev/tree/tentative/sheepdog
When there is a `SyntaxError` with acorn, it would be nice to know the file so that it give some hints.
Could it be because I'm using decorators ? Maybe there is the need of `'decorators-legacy'` or something ?

**Comment by paoloricciuti** [comment]
@jycouet we fixed it already...we were `console.error` when acorn failed to parse but that happens with every non js file so we removed it (we have to publish tho)

**Comment by jycouet** [comment]
Perfect, thank you 👍

**Comment by paoloricciuti** [comment]
I'm gonna close this @jycouet, thanks for reporting

**Comment by jycouet** [comment]
When will you release it? :D

**Comment by paoloricciuti** [comment]
> When will you release it? :D

Soon ™ (it'll probably be today)

But to be clear the error it's there but it's not affecting functionality, is just a console.error 😄

**Comment by jycouet** [comment]
Yes yes, I got that it's just a console log.
But I can merge only when my logs are cleared (it's not urgent tho ^^)

**Comment by paoloricciuti** [comment]
> Yes yes, I got that it's just a console log. But I can merge only when my logs are cleared (it's not urgent tho ^^)

Oh gotcha...yeah i think we will publish this in a couple of hours at max

**Comment by paoloricciuti** [comment]
@jycouet released!

**Comment by jycouet** [comment]
https://github.com/jycouet/jyc.dev/pull/11 merged! 🎉
Thank you ;)
